repos:
-    repo: https://github.com/psf/black
     rev: 23.1.0
     hooks:
     -    id: black
          args:
          -    --line-length=79
     -    id: black-jupyter
-    repo: https://github.com/PyCQA/flake8
     rev: 6.0.0
     hooks:
     -    id: flake8
          args: 
          -    "--ignore=E203,E402,W503,F401,E731"
          -    "--max-line-length=119"
-    repo: https://github.com/PyCQA/isort
     rev: 5.12.0
     hooks:
     -    id: isort
          name: isort (python)
          args: ["--profile", "black", "-v"]